version: "3.7"

services:
  freecad:
    image: linuxserver/freecad:1.1.1
    container_name: freecad
    ports:
      - "5133:3001"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - freecad_config:/config
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  freecad_config: