telegram:
  destination: ${TELEGRAM_WEBHOOK_URL}
  methods:
    - POST
  authorizedChatIds: ${TELEGRAM_AUTHORIZED_CHAT_IDS}
  authorizedUsernames: ${TELEGRAM_AUTHORIZED_USERNAMES}
  filter: telegramFilter

webhook-test:
  destination: ${N8N_WEBHOOK_URL}
  methods:
    - POST
  authorizedChatIds: ${TELEGRAM_AUTHORIZED_CHAT_IDS}
  authorizedUsernames: ${TELEGRAM_AUTHORIZED_USERNAMES}
  filter: telegramFilter

webhook:
  destination: ${N8N_WEBHOOK_URL}
  methods:
    - POST
  authorizedChatIds: ${TELEGRAM_AUTHORIZED_CHAT_IDS}
  authorizedUsernames: ${TELEGRAM_AUTHORIZED_USERNAMES}
  filter: telegramFilter

alexa:
  destination: ${ALEXA_WEBHOOK_URL}
  methods:
    - POST
  applicationId: ${ALEXA_APPLICATION_ID}
  filter: alexaskillFilter

substream:
  destination: ${SUBSTREAM_WEBHOOK_URL}
  methods:
    - POST
    - GET
  subdomain:
    - path: rest/ping.view
      filter: noFilter
  filter: noFilter
