version: "3.7"

services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    ports:
      - "5131:5000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PLAYWRIGHT_DRIVER_URL=ws://playwright:3000 
    volumes:
      - changedetection:/config
    restart: unless-stopped
    depends_on:
      - playwright

  playwright: 
    hostname: playwright
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    tmpfs:
      - /tmp   
    environment:
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1024
        - SCREEN_DEPTH=16
        - MAX_CONCURRENT_CHROME_PROCESSES=10
        - STATS_REFRESH_SECONDS=120

volumes:
  changedetection: