/**
 * Service para gerar MCPs customizados dinamicamente
 * Cria um arquivo .js pronto para ser executado em um container
 */

export interface CustomToolParameter {
  type: 'string' | 'number' | 'boolean' | 'object';
  description: string;
  required?: boolean;
  enum?: string[];
  default?: any;
}

export interface CustomToolMethod {
  name: string;
  description: string;
  parameters: Record<string, CustomToolParameter>;
  code: string; // JavaScript code for the tool implementation
}

export interface CustomToolDefinition {
  name: string;
  description?: string;
  methods: CustomToolMethod[];
  port?: number;
}

/**
 * Validates a custom tool definition
 */
export function validateCustomToolDefinition(def: CustomToolDefinition): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!def.name || typeof def.name !== 'string' || def.name.trim().length === 0) {
    errors.push('MCP name is required and must be a non-empty string');
  }

  if (!Array.isArray(def.methods) || def.methods.length === 0) {
    errors.push('At least one method is required');
  }

  def.methods?.forEach((method, idx) => {
    if (!method.name || typeof method.name !== 'string') {
      errors.push(`Method ${idx}: name is required and must be a string`);
    }

    if (!method.description || typeof method.description !== 'string') {
      errors.push(`Method ${idx} (${method.name}): description is required`);
    }

    if (!method.code || typeof method.code !== 'string') {
      errors.push(`Method ${idx} (${method.name}): code is required`);
    }

    if (!method.parameters || typeof method.parameters !== 'object') {
      errors.push(`Method ${idx} (${method.name}): parameters must be an object`);
    }
  });

  if (def.port !== undefined) {
    if (typeof def.port !== 'number' || !Number.isInteger(def.port)) {
      errors.push('Port must be an integer');
    } else if (def.port < 1024 || def.port > 65535) {
      errors.push('Port must be between 1024 and 65535');
    }
  }

  // Validate JavaScript code syntax
  def.methods?.forEach((method, idx) => {
    if (method.code) {
      try {
        // Try to create a function with the code to validate syntax
        // Get parameter names to pass to the function
        const paramNames = Object.keys(method.parameters || {});
        // eslint-disable-next-line no-new-func
        new Function(...paramNames, method.code);
      } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        errors.push(`Method ${idx} (${method.name}): Invalid JavaScript code - ${errorMsg}`);
      }
    }
  });

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Generates the JavaScript code for the custom MCP
 */
export function generateCustomMcpCode(definition: CustomToolDefinition): string {
  const { name, description = 'Custom MCP', methods } = definition;

  // Build CUSTOM_TOOLS array
  const toolsArray = methods
    .map((method) => {
      const params = Object.entries(method.parameters)
        .map(([paramName, param]) => {
          return `      ${paramName}: {
        type: '${param.type}',
        description: '${escapeString(param.description)}',${param.required ? "\n        required: true," : ""}${param.enum ? `\n        enum: [${param.enum.map((e) => `'${e}'`).join(', ')}],` : ""}${param.default !== undefined ? `\n        default: ${JSON.stringify(param.default)},` : ""}
      }`;
        })
        .join(',\n');

      const requiredParams = Object.entries(method.parameters)
        .filter(([_, p]) => p.required)
        .map(([name]) => `'${name}'`);

      return `  {
    name: '${method.name}',
    description: '${escapeString(method.description)}',
    inputSchema: {
      type: 'object',
      properties: {
${params}
      },
      required: [${requiredParams.join(', ')}],
    },
  }`;
    })
    .join(',\n');

  // Build switch cases for tool execution
  const cases = methods
    .map((method) => {
      const paramDestructure = Object.keys(method.parameters)
        .map((p) => `${p}`)
        .join(', ');

      return `      case '${method.name}': {
        const { ${paramDestructure} } = args;
        ${method.code}
      }`;
    })
    .join('\n\n');

  const code = `#!/usr/bin/env node
/**
 * Custom MCP: ${escapeString(name)}
 *
 * Auto-generated by MCP Hub Custom Tools Creator
 *
 * Methods:
${methods.map((m) => `   * - ${m.name}: ${m.description}`).join('\n')}
 */

const http = require('node:http');

const PORT = process.env.PORT || 8000;

const CUSTOM_TOOLS = [
${toolsArray}
];

console.log(\`[Custom MCP] Starting on port \${PORT}\`);
console.log(\`[Custom MCP] Available tools: \${CUSTOM_TOOLS.map((t) => t.name).join(', ')}\`);

const server = http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Content-Type', 'application/json');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method !== 'POST') {
    res.writeHead(405);
    res.end(JSON.stringify({ error: 'Method not allowed' }));
    return;
  }

  const path = req.url.split('?')[0];

  if (path === '/mcp' || path === '/') {
    let body = '';

    req.on('data', (chunk) => {
      body += chunk.toString();
    });

    req.on('end', async () => {
      try {
        const payload = JSON.parse(body);
        const response = await handleMcpRequest(payload);
        res.writeHead(200);
        res.end(JSON.stringify(response));
      } catch (error) {
        console.error('[Custom MCP] Error:', error.message);
        res.writeHead(500);
        res.end(
          JSON.stringify({
            jsonrpc: '2.0',
            error: {
              code: -32603,
              message: error.message,
            },
          })
        );
      }
    });
  } else {
    res.writeHead(404);
    res.end(JSON.stringify({ error: 'Not found' }));
  }
});

async function handleMcpRequest(payload) {
  const { jsonrpc = '2.0', id, method, params } = payload;

  switch (method) {
    case 'initialize':
      return {
        jsonrpc,
        id,
        result: {
          protocolVersion: '2024-11-05',
          capabilities: {
            tools: {},
          },
          serverInfo: {
            name: '${escapeString(name)}',
            version: '1.0.0',
          },
        },
      };

    case 'tools/list':
      return {
        jsonrpc,
        id,
        result: {
          tools: CUSTOM_TOOLS,
        },
      };

    case 'tools/call': {
      const toolName = params?.name;
      const toolArgs = params?.arguments || {};

      const result = await executeCustomTool(toolName, toolArgs);

      return {
        jsonrpc,
        id,
        result: {
          content: [
            {
              type: 'text',
              text: result,
            },
          ],
        },
      };
    }

    case 'resources/list':
      return {
        jsonrpc,
        id,
        result: {
          resources: [],
        },
      };

    case 'prompts/list':
      return {
        jsonrpc,
        id,
        result: {
          prompts: [],
        },
      };

    default:
      return {
        jsonrpc,
        id,
        error: {
          code: -32601,
          message: \`Method not implemented: \${method}\`,
        },
      };
  }
}

async function executeCustomTool(toolName, args) {
  try {
    switch (toolName) {
${cases}

      default:
        return JSON.stringify({
          error: \`Tool "\${toolName}" not found\`,
        });
    }
  } catch (error) {
    return JSON.stringify({
      error: \`Error executing tool: \${error.message}\`,
    });
  }
}

server.listen(PORT, '0.0.0.0', () => {
  console.log(\`[Custom MCP] Server listening on http://0.0.0.0:\${PORT}/mcp\`);
});

process.on('SIGTERM', () => {
  console.log('[Custom MCP] Received SIGTERM, shutting down');
  server.close(() => process.exit(0));
});

process.on('SIGINT', () => {
  console.log('[Custom MCP] Received SIGINT, shutting down');
  server.close(() => process.exit(0));
});
`;

  return code;
}

/**
 * Escapes special characters in strings for JavaScript
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Generates a Dockerfile for the custom MCP
 */
export function generateDockerfile(port: number = 8000): string {
  return `FROM node:20-alpine

WORKDIR /app

COPY server.js .

ENV PORT=${port}
EXPOSE ${port}

CMD ["node", "server.js"]
`;
}

/**
 * Full example of generated code
 */
export function generateExampleCustomTool(): CustomToolDefinition {
  return {
    name: 'Example Custom Tools',
    description: 'Example custom tools MCP',
    methods: [
      {
        name: 'greet',
        description: 'Greets a user by name',
        parameters: {
          name: {
            type: 'string',
            description: 'User name',
            required: true,
          },
          style: {
            type: 'string',
            description: 'Greeting style',
            enum: ['formal', 'casual', 'enthusiastic'],
          },
        },
        code: `const greetings = {
          formal: \`Dear \${name}, it's a pleasure to meet you.\`,
          casual: \`Hey \${name}! What's up?\`,
          enthusiastic: \`OMG \${name.toUpperCase()}!!! 🎉\`,
        };
        return greetings[style] || greetings.casual;`,
      },
      {
        name: 'calculate_discount',
        description: 'Calculates discount on a price',
        parameters: {
          original_price: {
            type: 'number',
            description: 'Original price',
            required: true,
          },
          discount_percent: {
            type: 'number',
            description: 'Discount percentage',
            required: true,
          },
        },
        code: `const discount_amount = original_price * (discount_percent / 100);
        const final_price = original_price - discount_amount;
        return JSON.stringify({
          original_price,
          discount_percent,
          discount_amount: discount_amount.toFixed(2),
          final_price: final_price.toFixed(2),
        });`,
      },
    ],
  };
}
