version: "3.7"

services:
  webtop:
    image: linuxserver/webtop:arm64v8-fedora-kde
    container_name: webtop
    ports:
      - "5134:3001"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - webtop_config:/config
    shm_size: "1gb"
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

volumes:
  webtop_config: